apiVersion: v1
kind: ConfigMap
metadata:
  name: ddl-sql
  namespace: database
data:
  init.sql: |
    CREATE TABLE healthcheck (id serial PRIMARY KEY, status varchar(50) NOT NULL);
    INSERT INTO healthcheck (status) VALUES ('OK');
    CREATE TABLE favorite_colors (id serial PRIMARY KEY, name varchar(50) NOT NULL, color varchar(50) NOT NULL);
    INSERT INTO favorite_colors (name, color) VALUES ('Lancelot', 'blue'), ('Galahad', 'yellow');