apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: lab-webui:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Never
